# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.urbanstack.co:
  peer0.aphp.urbanstack.co:
  peer1.aphp.urbanstack.co:
  peer0.org2.urbanstack.co:
  peer1.org2.urbanstack.co:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-aphp
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.aphp.urbanstack.co-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a07939fa561623a06254438630ac1d6aef8b1ca58471bc8518ee1d1fcbb29d12_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.aphp.urbanstack.co-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a07939fa561623a06254438630ac1d6aef8b1ca58471bc8518ee1d1fcbb29d12_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/aphp.urbanstack.co/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerAphp
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.urbanstack.co-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a0b10417a87c26df7579010fd4d6a7571f222035f51185a82b4cc471096de4b5_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.urbanstack.co-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a0b10417a87c26df7579010fd4d6a7571f222035f51185a82b4cc471096de4b5_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.urbanstack.co/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn

  orderer.urbanstack.co:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.urbanstack.co
    container_name: orderer.urbanstack.co
    networks:
      - byfn

  peer0.aphp.urbanstack.co:
    container_name: peer0.aphp.urbanstack.co
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.aphp.urbanstack.co
    networks:
      - byfn

  peer1.aphp.urbanstack.co:
    container_name: peer1.aphp.urbanstack.co
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.aphp.urbanstack.co
    networks:
      - byfn

  peer0.org2.urbanstack.co:
    container_name: peer0.org2.urbanstack.co
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.urbanstack.co
    networks:
      - byfn

  peer1.org2.urbanstack.co:
    container_name: peer1.org2.urbanstack.co
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.urbanstack.co
    networks:
      - byfn
