# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.morpheo.co:
  peer0.aphp.morpheo.co:
  peer1.aphp.morpheo.co:
  peer0.org2.morpheo.co:
  peer1.org2.morpheo.co:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-aphp
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.aphp.morpheo.co-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e57cb461df885c968c4224eaad15e02a029288e29a59ab42a0c0d95cc644e80e_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.aphp.morpheo.co-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/e57cb461df885c968c4224eaad15e02a029288e29a59ab42a0c0d95cc644e80e_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/aphp.morpheo.co/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerAphp
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.morpheo.co-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8fadb9eadd14bc1e2489e7976f79fe430c7aa67b4597ba5220fb8874c287281b_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.morpheo.co-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/8fadb9eadd14bc1e2489e7976f79fe430c7aa67b4597ba5220fb8874c287281b_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.morpheo.co/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn

  orderer.morpheo.co:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.morpheo.co
    container_name: orderer.morpheo.co
    networks:
      - byfn

  peer0.aphp.morpheo.co:
    container_name: peer0.aphp.morpheo.co
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.aphp.morpheo.co
    networks:
      - byfn

  peer1.aphp.morpheo.co:
    container_name: peer1.aphp.morpheo.co
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.aphp.morpheo.co
    networks:
      - byfn

  peer0.org2.morpheo.co:
    container_name: peer0.org2.morpheo.co
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.morpheo.co
    networks:
      - byfn

  peer1.org2.morpheo.co:
    container_name: peer1.org2.morpheo.co
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.morpheo.co
    networks:
      - byfn
